connect my_database


-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE tbl_permission_id_seq;

CREATE SEQUENCE tbl_permission_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_role_id_seq;

CREATE SEQUENCE tbl_role_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_user_id_seq;

CREATE SEQUENCE tbl_user_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;-- public.tbl_permission definition

-- Drop table

-- DROP TABLE tbl_permission;

CREATE TABLE tbl_permission (
                                created_date int8 NOT NULL,
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                modified_date int8 NULL,
                                permission_key varchar(255) NULL,
                                permission_name varchar(255) NULL,
                                CONSTRAINT tbl_permission_pkey PRIMARY KEY (id)
);


-- public.tbl_role definition

-- Drop table

-- DROP TABLE tbl_role;

CREATE TABLE tbl_role (
                          created_date int8 NOT NULL,
                          id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                          modified_date int8 NULL,
                          role_key varchar(255) NULL,
                          role_name varchar(255) NULL,
                          CONSTRAINT tbl_role_pkey PRIMARY KEY (id)
);


-- public.tbl_user definition

-- Drop table

-- DROP TABLE tbl_user;

CREATE TABLE tbl_user (
                          created_date int8 NOT NULL,
                          id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                          modified_date int8 NULL,
                          flag_del varchar(255) NULL,
                          password_login varchar(255) NOT NULL,
                          status varchar(255) NULL,
                          username_login varchar(255) NOT NULL,
                          CONSTRAINT tbl_user_pkey PRIMARY KEY (id)
);


-- public.tbl_role_permission definition

-- Drop table

-- DROP TABLE tbl_role_permission;

CREATE TABLE tbl_role_permission (
                                     permission_id int8 NOT NULL,
                                     role_id int8 NOT NULL,
                                     CONSTRAINT tbl_role_permission_pkey PRIMARY KEY (permission_id, role_id),
                                     CONSTRAINT fkederj3igpg2d7b1llsoibhb2x FOREIGN KEY (permission_id) REFERENCES tbl_permission(id),
                                     CONSTRAINT fkey6ucxnb0cg80jar6tje0k82e FOREIGN KEY (role_id) REFERENCES tbl_role(id)
);


-- public.tbl_user_role definition

-- Drop table

-- DROP TABLE tbl_user_role;

CREATE TABLE tbl_user_role (
                               role_id int8 NOT NULL,
                               user_id int8 NOT NULL,
                               CONSTRAINT tbl_user_role_pkey PRIMARY KEY (role_id, user_id),
                               CONSTRAINT fk6phlytlf1w3h9vutsu019xor5 FOREIGN KEY (role_id) REFERENCES tbl_role(id),
                               CONSTRAINT fkggc6wjqokl2vlw89y22a1j2oh FOREIGN KEY (user_id) REFERENCES tbl_user(id)
);